basePath: /api
consumes:
    - application/json
info:
    license:
        name: GPLV3
        url: https://www.gnu.org/licenses/gpl-3.0.en.html
    termsOfService: there are no TOS at this moment, use at your own risk we take no responsibility
    title: Receipt Wrangler API.
    version: 0.0.1
paths:
    /notifications/:
        delete:
            description: This deletes all notifications for a user
            operationId: notificationCount
            responses:
                "200":
                    $ref: '#/responses/Ok'
                "500":
                    $ref: '#/responses/Internal'
                    description: Server Error
            schemes:
                - https
            security:
                - api_key: []
            summary: Delete all notifications for user
            tags:
                - Notifications
        get:
            consumes:
                - application/json
            description: This will get all the notifications for the currently logged in user
            operationId: listNotifications
            produces:
                - application/json
            responses:
                "200":
                    $ref: '#/responses/Ok'
                "500":
                    $ref: '#/responses/Internal'
                    description: Server Error
            schemes:
                - https
            security:
                - api_key: []
            summary: Get all user notifications
            tags:
                - Notifications
    /notifications/{id}:
        delete:
            description: This deletes a notification by id
            operationId: notificationCount
            responses:
                "200":
                    $ref: '#/responses/Ok'
                "500":
                    $ref: '#/responses/Internal'
                    description: Server Error
            schemes:
                - https
            security:
                - api_key: []
            summary: Delete notification by id
            tags:
                - Notifications
    /notifications/notificationCount:
        get:
            description: This will get the notification count for the currently logged in user
            operationId: notificationCount
            produces:
                - text/plain
            responses:
                "200":
                    $ref: '#/responses/Ok'
                "500":
                    $ref: '#/responses/Internal'
                    description: Server Error
            schemes:
                - https
            security:
                - api_key: []
            summary: Notification count
            tags:
                - Notifications
    /search:
        get:
            consumes:
                - text/plain
            description: This will search for receipts based on a search term
            operationId: search
            parameters:
                - description: search term
                  in: query
                  name: searchTerm
                  required: true
                  type: string
            produces:
                - application/json
            responses:
                "200":
                    $ref: '#/responses/Ok'
                "500":
                    $ref: '#/responses/Internal'
                    description: Server Error
            schemes:
                - https
            security:
                - api_key: []
            summary: Receipt Search
            tags:
                - Search
produces:
    - application/json
schemes:
    - https
security:
    - api_key: []
securityDefinitions:
    api_key:
        in: header
        name: jwt
        type: string
swagger: "2.0"
