/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Status of a receipt
 */
export type ReceiptStatus = 'OPEN' | 'NEEDS_ATTENTION' | 'RESOLVED' | 'DRAFT' | 'DECLINED' | '';

export const ReceiptStatus = {
    Open: 'OPEN' as ReceiptStatus,
    NeedsAttention: 'NEEDS_ATTENTION' as ReceiptStatus,
    Resolved: 'RESOLVED' as ReceiptStatus,
    Draft: 'DRAFT' as ReceiptStatus,
    Declined: 'DECLINED' as ReceiptStatus,
    Empty: '' as ReceiptStatus
};

